use_frameworks!

platform :ios, '9.0'

target 'YLBasedComponent_Example' do
  pod 'YLBasedComponent', :path => '../'

  target 'YLBasedComponent_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
